FROM mcr.microsoft.com/powershell:latest

#SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';"]

# COPY helloScript.ps1 'C:\\'

ENTRYPOINT ["powershell", "dir"]